// store
export const QUESTIONS_BRANCH = "QUESTIONS";
export const QUESTIONS_FETCHED = "QUESTIONS_FETCHED";
export const QUESTIONS = "QUESTIONS";

// actions
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_ERROR";
