// store
export const QUESTIONS_BRANCH = "QUESTIONS";
export const QUESTIONS_FETCHED = "QUESTIONS_FETCHED";
export const QUESTIONS = "QUESTIONS";
export const CURRENTLY_DISPLAYED_QUESTION_INDEX = "CURRENTLY_DISPLAYED_QUESTION_INDEX";

// actions
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_ERROR";
export const CHANGE_SHOWN_QUESTION_INDEX = "CHANGE_SHOWN_QUESTION_INDEX";
