// store
export const QUESTIONS_BRANCH = "QUESTIONS";
export const QUESTIONS_FETCHED = "QUESTIONS_FETCHED";
export const QUESTIONS = "QUESTIONS";
export const CURRENTLY_DISPLAYED_QUESTION_INDEX = "CURRENTLY_DISPLAYED_QUESTION_INDEX";
export const TEST_STARTED = "TEST_STARTED";
export const CORRECT_ANSWERS = "CORRECT_ANSWERS";
export const TOTAL_GRADE = "TOTAL_GRADE";
export const USER_ANSWERS = "USER_ANSWERS";

// actions
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_ERROR = "FETCH_QUESTIONS_ERROR";
export const CHANGE_SHOWN_QUESTION_INDEX = "CHANGE_SHOWN_QUESTION_INDEX";
export const BEGIN_TEST = "BEGIN_TEST";
export const END_TEST = "END_TEST";
export const MARK_USER_ANSWER = "MARK_USER_ANSWER";
